services:
  redis:
    image: redis:8.2
    container_name: chat_backend_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - chat_backend_redis:/data

  postgres_user_service:
    image: postgres:16
    container_name: user_service_chat_backend_postgres
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_database
    ports:
      - "5432:5432"
    volumes:
      - auth_database:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d

volumes:
  chat_backend_redis:
  auth_database:
