server:
  port: 1337

spring:
  application:
    name: chat_backend

  datasource:
    url: "jdbc:postgresql://localhost:5432/auth_database"
    username: "max"
    password: "password"
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

jwt:
  secret: "PSbBLHwCd06Wgbv8LhKedSWRoPMv8rtmlvcEJLVo/5J0/CLUHLvNTl31lMzrDhOkgLG6HJPb1GUiOHNAjC7W3A=="
  expiration-minutes: 150

email:
  verification:
    expiry-hours: 24
  reset-password:
    expiry-minutes: 30

data:
  redis:
    host: "localhost"
    port: "6379"
    connect-timeout: 5000ms
    timeout: 2000ms

nginx:
  require-proxy: true
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"